### PR TITLE
Release/prepobs.v1.0.0 rm

### PR DESCRIPTION
**Pull request by ilianagenkova**
Restructured prepobs to meet programing standards:
- README.md and Release_Notes.txt in /docs now
- build.sh is in /ush
- updated README.md and Release_Notes.txt contents

### CODE REVIEW

**Review by AshleyStanfield-NOAA — APPROVED** [review]

**Review by dmerkova — APPROVED** [review]
looks good to me

**Review by aerorahul — APPROVED** [review]
looks good.

**Comment by aerorahul** [comment]
@ilianagenkova 
I had approved this on Sept 19, 2022 based on the state of the PR then.
I see since then commits have been made.
Particularly, there has been a commit where compiled executables (under `exec/`) have been added.  I would not have approved the PR if that was the case.
Is there a reason why compiled executables need to be version-controlled? Besides, these executables are most likely for WCOSS2, whereas the repository is capable of being built and run on multiple HPCs.
I suggest removing the compiled executables from the repository, cleaning out the cache and refraining from committing executables to this (or any other) repository in the future.

**Comment by ilianagenkova** [comment]
@aerorahul It was not intentional to have /install & executables added to the branch in GitHub. I deleted the branch and will now review the rest of our branches across all 5 repos I manage. Thanks for letting me know.

**Pull request merged**
