### PR TITLE
Add/update files to build and run prepobs on Gaea C5

### LINKED ISSUE #32: Setup prepobs dev/gfsv17 to compile and run C96_atm3DVar CI test on Gaea-C5
Update build files and add Gaea-specific module files to compile and run prepobs branch dev/gfsv17 C96_atm3DVar on Gaea-C5

Ref NOAA-EMC/global-workflow [#2766](https://github.com/NOAA-EMC/global-workflow/issues/2766)

### PR DESCRIPTION
**Pull request by DavidBurrows-NCO**
Added modulefiles/prepobs_gaea.lua to build prepobs on Gaea-C5.  Spack-stack gsi-addon-dev environment used for bufr/11.7.0.
Tested with C96_atm3DVar.yaml experiment from the global-workflow CI tests.

Refs #32 
Refs NOAA-EMC/global-workflow [#2766](https://github.com/NOAA-EMC/global-workflow/issues/2766)

I'm starting this PR in draft mode. Gaea-C5 will only be supporting a legacy ksh version, which does not support regex expressions (extended globbing is supported instead.)  For this reason, `prepobs/v1.0.2/install/ush/prepobs_makeprepbufr.sh` silently fails with `[1620]: syntax error: unexpected operator/operand '=~'` on this line: `if [[ "$COMSP" =~ (^/com/|^/com2/|^/gpfs/.../nco/ops/com/)`.  The C96_atm3DVar workflow still completes successfully.  I'm tracking a ticket with Gaea SA, and hopefully will resolve this set back soon.

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
looks good. thanks!

**Review by KateFriedman-NOAA — APPROVED** [review]
Updates look good, thanks @DavidBurrows-NCO !

I will recut the `prepobs.v1.1.0-rd-gfsv17` tag after this goes in so you can install that tag as `v1.1.0` on Gaea for users.

**Comment by KateFriedman-NOAA** [comment]
@DavidBurrows-NCO did you want me to wait to merge this because of the `ksh` issue? I am opening issues in obsproc/prepobs to request that they convert to `bash`.

**Comment by DavidBurrows-NCO** [comment]
@KateFriedman-NOAA Since it's not causing failures in the workflow, I think it's okay to go ahead and merge. If you see any issues with that, please let me know. Thanks.

**Comment by KateFriedman-NOAA** [comment]
Okie dokie, I'll proceed with merging and recutting the tag. Thanks @DavidBurrows-NCO !

**Pull request merged**
