### PR TITLE
Generate modulefile with CMake

### PR DESCRIPTION
**Pull request by kgerheiser**
This is the only problem I see. Are you having any other issue building @ShelleyMelchior-NOAA?

### CODE REVIEW

**Comment by kgerheiser** [comment]
I am getting the same error.

Strangely though, it shows `bacio/2.4.1` as loaded.

Same build works on Hera.

**Comment by kgerheiser** [comment]
This doesn't make any sense. In `build.sh` I can see `bacio_ROOT` set and the module loaded, but CMake isn't picking it up from within the script. Building with the same modules manually, and CMake finds bacio.

**Comment by kgerheiser** [comment]
@ShelleyMelchior-NOAA I fixed the problem. Had to load the `envvar` module on WCOSS2.

**Comment by kgerheiser** [comment]
Build works on Orion, Hera, and WCOSS2.

**Comment by ShelleyMelchior-NOAA** [comment]
Excellent -- I can now build on wcoss2, too. I will approve and merge this PR.

**Pull request merged**
